name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t loanbot:${{ github.sha }} .

      # OPTIONAL – push to GHCR (needs write-packages permission + PAT in secrets)
      # - name: Log in to GHCR
      #   run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # - name: Push image
      #   run: docker tag loanbot:${{ github.sha }} ghcr.io/${{ github.repository }}:latest && \
      #        docker push ghcr.io/${{ github.repository }}:latest
