name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:     
      id-token: write
      contents: read

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    # ── Python unit tests ─────────────────────────────────────
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps & run pytest
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt
        pytest -q

    # ── Docker build (local only) ─────────────────────────────
    - name: Build Docker image
      run: docker build -t loanbot:${{ github.sha }} .

    # ── (Optional) push image to ACR ──────────────────────────
    - name: Azure login (OIDC)
      if: ${{ env.ACR_NAME != '' }}
      uses: azure/login@v2
      with:
        tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
        subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id:        ${{ secrets.AZURE_CLIENT_ID }}

    - name: Push image to ACR
      if: ${{ env.ACR_NAME != '' }}
      run: |
        az acr login --name ${{ env.ACR_NAME }}
        docker tag loanbot:${{ github.sha }} ${{ env.ACR_NAME }}.azurecr.io/loanbot:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/loanbot:${{ github.sha }}

  # ── (Optional) run pytest **inside** AML env instead of locally ─────────
  aml-test:
    if: ${{ false }}        # flip to true when you want AML runs
    needs: test-and-build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
        tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
        subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id:        ${{ secrets.AZURE_CLIENT_ID }}

    - name: Install AML CLI
      run: az extension add -n ml -y

    - name: Submit pytest job to AML
      run: |
        az ml job create \
          --file .azureml/test_job.yml \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_WORKSPACE }} \
          --set name=loanbot-smoke-${{ github.run_number }}
